-- -- define your colorscheme here
-- local colorscheme = "slate" -- monokai_pro -- catppuccin-mocha -- unokai -- slate -- torte -- tokyonight-storm
--
-- local is_ok, _ = pcall(vim.cmd, "colorscheme " .. colorscheme)
-- if not is_ok then
--   vim.notify("colorscheme " .. colorscheme .. " not found!")
--   return
-- end
vim.cmd.colorscheme "catppuccin-frappe"
-- monokai_pro
-- catppuccin-mocha
-- unokai
-- slate
-- torte
-- tokyonight-storm
